### ISSUE TITLE
Sounds doesnt play

### ISSUE THREAD

**Issue by Slmb6** [Joey79100/trle-aod_animations#8]
I have an issue with sounds of the animations, some (most of them actually) aren't playing, i follow the steps to add them to my project, but most of them are still missing, what am i doing wrong ?

**Comment by JoeyQuint** [comment]
It is the first time I'm seeing this (or maybe I saw it when I couldn't reply and forgot), sorry about this.
But please refer to Discord TRLE servers or other TRLE communities, opening an issue is reserved only for problems / improvements specific to the animations, while your question seems to be more a "how to use TRLE" type of question.
